# [START django_app]
service: hasnain-django-react1
runtime: python38
handlers:


- url: /front-todo/build/static
  static_dir: front-todo/build/static/
- url: /.*
  static_files: front-todo/build/static
  script: auto

entrypoint: gunicorn -b :$PORT core.wsgi