# [START django_app]
service: hasnain-django-react1
runtime: python38
handlers:


- url: /(.*\..+)$
  static_files: front-todo/build/\1
  upload: front-todo/build/(.*\..+)$
# Catch all handler to index.html
- url: /.*
  static_files: front-todo/build/index.html
  upload: front-todo/build/index.html
  
  
entrypoint: gunicorn -b :$PORT core.wsgi