# [START django_app]
service: hasnain-django-react
runtime: python38
handlers:

- url: /static
  static_dir: static/
- url: /.*
#  static_files: /front-todo/build/index.html
  script: auto

entrypoint: gunicorn -b :$PORT core.wsgi