# [START django_app]
service: hasnain-django-react2
runtime: python38
handlers:


- url: /front-todo/build
  static_dir: front-todo/build/
- url: /.*
  script: auto

entrypoint: gunicorn -b :$PORT core.wsgi